site_name: TITR 资料库

nav:
  - 主页:
      - 简介: index.md
  - 环境安装:
      - Linux: ubuntu/Ubuntu.md
      - OpenCV: ubuntu/OpenCV.md
      - Azure Kinect DK: ubuntu/Azure Kinect DK 深度相机.md
theme:
  # 主题
  name: material
  # 语言
  language: zh
  # 切换亮/暗模式。
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  # 标签栏设置
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    # 代码复制按钮
    - content.code.copy
