name: TITR

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install jinja2~=3.0
          pip install markdown~=3.2
          pip install mkdocs~=1.5.3
          pip install mkdocs-material-extensions~=1.3
          pip install pygments~=2.16
          pip install pymdown-extensions~=10.2
          pip install babel~=2.10
          pip install colorama~=0.4
          pip install paginate~=0.5
          pip install regex>=2022.4
          pip install requests~=2.26
          pip install mkdocs-material
          pip install mkdocs-markdownextradata-plugin

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
